export type TCourseSection = {
    heading?: string;
    paragraphs?: string[];
    bullets?: string[];
};

export type TLesson = {
    id: string;
    tag: string;
    title: string;
    intro?: string;
    sections: TCourseSection[];
    keyTakeaway?: string;
};

export const LESSONS: TLesson[] = [
    {
        id: 'l1',
        tag: 'Getting Started',
        title: '1. What Is Deriv and How Trading Works Here',
        intro: 'Deriv is an online broker that lets you trade financial and synthetic markets through contracts, without owning the underlying asset.',
        sections: [
            {
                heading: 'The big picture',
                paragraphs: [
                    'When you trade on Deriv, you are not buying shares or currency in the traditional sense. Instead, you open a contract that pays out based on how the price of an asset moves. This applies whether you trade forex, stocks, commodities, or Deriv\'s own synthetic indices.',
                    'Deriv offers two main trading experiences: Deriv Trader, a simple point-and-click interface for options and multipliers, and Deriv Bot (DBot), a drag-and-drop tool for building automated trading strategies without writing code.',
                ],
            },
            {
                heading: 'Core building blocks of every trade',
                bullets: [
                    'Market — the asset you are trading, e.g. Volatility 75 Index or EUR/USD.',
                    'Contract type — the rule that decides how you win or lose, e.g. Rise/Fall or Touch/No Touch.',
                    'Stake — the amount of money you risk on the trade.',
                    'Duration — how long the contract runs, measured in ticks, seconds, minutes, hours, or days.',
                    'Payout — what you receive if the contract ends in your favour.',
                ],
            },
        ],
        keyTakeaway: 'Every Deriv trade is a combination of market + contract type + stake + duration. Master these four pieces and you can understand any trade on the platform.',
    },
    {
        id: 'l2',
        tag: 'Synthetic Markets',
        title: '2. Understanding Synthetic Indices',
        intro: 'Synthetic indices are simulated markets generated by a random number algorithm, designed to mimic real market volatility around the clock.',
        sections: [
            {
                heading: 'Why synthetics exist',
                paragraphs: [
                    'Real markets close on weekends and holidays, and can be affected by news events, illiquidity, or manipulation. Deriv created synthetic indices to give traders a market that behaves statistically like a real one but is available 24 hours a day, 7 days a week, including weekends.',
                    'Because synthetic indices are generated by a certified random number generator, their long-term statistical properties (such as volatility) are fixed and published, which makes them attractive for traders who want predictable market behaviour to practise and test strategies on.',
                ],
            },
            {
                heading: 'Families of synthetic indices',
                bullets: [
                    'Volatility Indices — continuous price feeds with a fixed volatility level.',
                    'Boom and Crash Indices — trending markets with sudden opposite spikes.',
                    'Step Index — moves in fixed small steps up or down.',
                    'Jump Indices — mostly calm with occasional sudden jumps.',
                    'Range Break Indices — stays in a range, then breaks out sharply.',
                ],
            },
        ],
        keyTakeaway: 'Synthetic indices are not real-world assets — they are mathematically generated markets, always open, with known and stable volatility characteristics.',
    },
    {
        id: 'l3',
        tag: 'Synthetic Markets',
        title: '3. Volatility Indices Explained (10, 25, 50, 75, 100)',
        intro: 'Volatility indices are the most commonly traded synthetic markets, each named after its annualised volatility level.',
        sections: [
            {
                heading: 'What the number means',
                paragraphs: [
                    'The number in the name, such as 10, 25, 50, 75 or 100, represents how volatile the index is. A higher number means bigger and faster price swings, while a lower number means calmer, slower movement. Volatility 10 is the gentlest, while Volatility 100 moves the most aggressively.',
                    'There are also 1-second versions (e.g. Volatility 75 (1s)) which generate a new tick every second instead of roughly every two seconds, making them faster-paced and suited to short-duration strategies.',
                ],
            },
            {
                heading: 'Choosing a volatility index',
                bullets: [
                    'Lower volatility (10, 25) — smoother price action, useful for beginners and slower strategies.',
                    'Medium volatility (50) — a balance between smoothness and movement.',
                    'Higher volatility (75, 100) — larger swings, higher potential reward but higher risk.',
                    '1-second indices — faster tick generation, ideal for scalping and tick-based bots.',
                ],
            },
        ],
        keyTakeaway: 'Match the volatility index to your strategy and risk tolerance: lower numbers for steadier trades, higher numbers for traders comfortable with sharper price swings.',
    },
    {
        id: 'l4',
        tag: 'Synthetic Markets',
        title: '4. Boom and Crash Indices',
        intro: 'Boom and Crash indices trend steadily in one direction and then experience a sudden, sharp spike in the opposite direction.',
        sections: [
            {
                heading: 'How they behave',
                paragraphs: [
                    'Boom indices (e.g. Boom 300, Boom 500, Boom 1000) generally trend downward, then experience a sudden upward spike at semi-random intervals. Crash indices (e.g. Crash 300, Crash 500, Crash 1000) generally trend upward, then experience a sudden downward spike.',
                    'The number in the name (300, 500, 1000) refers to the average frequency of ticks between spikes — a lower number means spikes occur more often. This makes Boom and Crash markets popular for both trend-following and spike-anticipating strategies.',
                ],
            },
            {
                heading: 'Common approaches',
                bullets: [
                    'Trend trading — riding the steady directional movement between spikes.',
                    'Spike anticipation — attempting to catch the sudden reversal, typically with tight risk control since spikes are not perfectly predictable.',
                    'Combining with Rise/Fall or Multiplier contracts depending on your risk appetite.',
                ],
            },
        ],
        keyTakeaway: 'Boom indices spike up, Crash indices spike down — the rest of the time they trend steadily in the opposite direction, which is the basis of most Boom/Crash strategies.',
    },
    {
        id: 'l5',
        tag: 'Synthetic Markets',
        title: '5. Step Index, Jump Indices, and Range Break Indices',
        intro: 'Beyond Volatility and Boom/Crash, Deriv offers several other synthetic markets with distinct movement patterns.',
        sections: [
            {
                heading: 'Step Index',
                paragraphs: [
                    'The Step Index moves in fixed-size increments, up or down, at every tick, with roughly equal probability of moving in either direction. This makes it popular for strategies based on counting consecutive same-direction moves or digit-style prediction contracts.',
                ],
            },
            {
                heading: 'Jump Indices',
                paragraphs: [
                    'Jump Indices behave like a calm volatility index most of the time, but occasionally make a sudden large jump up or down. The jump frequency and size differ by index (e.g. Jump 10, Jump 25, Jump 50, Jump 75, Jump 100).',
                ],
            },
            {
                heading: 'Range Break Indices',
                paragraphs: [
                    'Range Break Indices stay confined within a defined price range for a period, then break out of that range with a strong directional move, before settling into a new range. Traders use these for range-bound strategies and breakout detection.',
                ],
            },
        ],
        keyTakeaway: 'Each synthetic index family has a distinct personality — steps, jumps, or range breaks — so choose the one whose pattern matches the strategy you want to trade.',
    },
    {
        id: 'l6',
        tag: 'Real Markets',
        title: '6. Forex Trading on Deriv',
        intro: 'Deriv also offers real-world forex pairs, letting you trade currency movements using the same contract types as synthetic markets.',
        sections: [
            {
                heading: 'How forex differs from synthetics',
                paragraphs: [
                    'Forex pairs on Deriv, such as EUR/USD, GBP/JPY, or AUD/USD, track real currency exchange rates. Unlike synthetic indices, forex markets are affected by real-world events — central bank interest rate decisions, economic data releases, geopolitical news — and they follow standard market hours, closing on weekends.',
                    'Because real markets can gap or become volatile around news, risk management is especially important when trading forex compared to the more statistically predictable synthetic indices.',
                ],
            },
            {
                heading: 'Ways to trade forex on Deriv',
                bullets: [
                    'Options contracts — Rise/Fall, Touch/No Touch, and similar fixed-payout contracts.',
                    'Multipliers — leveraged exposure to price movement with a defined stop-out level.',
                    'CFDs (via Deriv MT5 or Deriv X) — traditional leveraged trading with variable position sizing.',
                ],
            },
        ],
        keyTakeaway: 'Forex on Deriv brings real-world market dynamics and news sensitivity, so factor economic calendars and market hours into your trading decisions.',
    },
    {
        id: 'l7',
        tag: 'Real Markets',
        title: '7. Stock Indices, Commodities, and Cryptocurrencies',
        intro: 'Deriv extends beyond forex and synthetics to give traders access to stock indices, commodities, and popular cryptocurrencies.',
        sections: [
            {
                heading: 'Stock indices and commodities',
                paragraphs: [
                    'Stock indices such as US 500 or Wall Street track baskets of major company shares, giving exposure to overall market sentiment without picking individual stocks. Commodities like Gold, Silver, and Oil are traded based on their real-world spot prices and are often used as a hedge against currency movements or inflation.',
                ],
            },
            {
                heading: 'Cryptocurrencies',
                paragraphs: [
                    'Deriv also lists major cryptocurrencies such as Bitcoin and Ethereum. Crypto markets trade 24/7 like synthetic indices, but their price action is driven by real supply, demand, and sentiment, and can be significantly more volatile than traditional assets.',
                ],
            },
            {
                heading: 'Why diversify across asset classes',
                bullets: [
                    'Different assets react to different drivers, reducing the chance that one single event affects your entire trading activity.',
                    'Some assets suit trending strategies, others suit range or reversal strategies.',
                    'Trading hours differ, so diversifying can also diversify the times you are able to trade.',
                ],
            },
        ],
        keyTakeaway: 'Stock indices, commodities, and crypto each carry their own real-world drivers — understanding what moves each market helps you choose the right one for your strategy.',
    },
    {
        id: 'l8',
        tag: 'Contract Types',
        title: '8. Rise/Fall and Higher/Lower Contracts',
        intro: 'Rise/Fall and Higher/Lower are the simplest and most widely used contract types on Deriv, forming the foundation for most beginner strategies.',
        sections: [
            {
                heading: 'Rise/Fall',
                paragraphs: [
                    'With a Rise/Fall contract, you predict whether the exit price at the end of the contract duration will be higher (Rise) or lower (Fall) than the entry price. It is a straightforward directional bet with a fixed payout if correct.',
                ],
            },
            {
                heading: 'Higher/Lower',
                paragraphs: [
                    'Higher/Lower is similar but uses a barrier level instead of the exact entry price. You predict whether the exit price will be higher or lower than a chosen barrier, which is often set away from the current price, changing the payout odds compared to Rise/Fall.',
                ],
            },
            {
                heading: 'When to use them',
                bullets: [
                    'Rise/Fall — best when you have a directional view but no specific price target.',
                    'Higher/Lower — useful when you want to set a specific barrier based on support/resistance or a technical level.',
                ],
            },
        ],
        keyTakeaway: 'Rise/Fall bets on direction from the entry price; Higher/Lower bets on direction relative to a chosen barrier — both are pure directional contracts.',
    },
    {
        id: 'l9',
        tag: 'Contract Types',
        title: '9. Touch/No Touch and In/Out Contracts',
        intro: 'These contracts let you trade on whether price will reach a certain level, or stay within/outside a defined range, rather than just its final direction.',
        sections: [
            {
                heading: 'Touch/No Touch',
                paragraphs: [
                    'A Touch contract pays out if the price touches a predefined barrier at any point during the contract period. A No Touch contract pays out if the price never touches that barrier. These are useful when you expect a breakout (Touch) or expect price to stay contained (No Touch).',
                ],
            },
            {
                heading: 'In/Out (Ends Between / Ends Outside, Stays Between / Goes Outside)',
                paragraphs: [
                    'In/Out contracts use two barriers instead of one. "Ends Between" pays if the exit price lands inside the two barriers, "Ends Outside" pays if it lands outside them. "Stays Between" and "Goes Outside" apply the same logic but consider the entire duration of the contract, not just the final price.',
                ],
            },
            {
                heading: 'Strategic use',
                bullets: [
                    'Touch — good for breakout or spike-anticipation strategies, such as around Boom/Crash spikes.',
                    'No Touch — good for range-bound, low-volatility conditions.',
                    'In/Out — useful when you have a defined expected trading range based on recent price history.',
                ],
            },
        ],
        keyTakeaway: 'Touch/No Touch and In/Out contracts let you trade on price behaviour throughout the whole duration, not just the final direction — ideal for range and breakout views.',
    },
    {
        id: 'l10',
        tag: 'Contract Types',
        title: '10. Digit Contracts: Matches/Differs, Over/Under, Odd/Even',
        intro: 'Digit contracts are unique to Deriv and let you predict the last digit of the exit price rather than the direction of the market.',
        sections: [
            {
                heading: 'How digit contracts work',
                paragraphs: [
                    'Every tick on Deriv ends in a specific last digit from 0 to 9. Digit contracts pay out based on your prediction of that final digit, making them fundamentally different from directional contracts — they are closer to probability-based predictions than trend trading.',
                ],
            },
            {
                heading: 'The main digit contract types',
                bullets: [
                    'Matches/Differs — predict whether the last digit will match or differ from a chosen digit.',
                    'Over/Under — predict whether the last digit will be over or under a chosen digit (0–9).',
                    'Odd/Even — predict whether the last digit will be odd or even.',
                ],
            },
            {
                heading: 'A word of caution',
                paragraphs: [
                    'Because each digit is close to independently random, digit trading is closer to probability play than technical analysis. Many traders use digit statistics (frequency tables shown on the platform) to inform decisions, but no digit sequence guarantees a future outcome — treat digit contracts with strict stake and loss limits.',
                ],
            },
        ],
        keyTakeaway: 'Digit contracts trade on the final digit of price, not its direction — approach them as probability-based trades and always use strict risk limits.',
    },
    {
        id: 'l11',
        tag: 'Contract Types',
        title: '11. Multipliers Explained',
        intro: 'Multipliers give you leveraged exposure to price movement, amplifying both potential profit and potential loss relative to your stake.',
        sections: [
            {
                heading: 'How multipliers work',
                paragraphs: [
                    'When you open a Multiplier contract, your stake is multiplied by a chosen factor (e.g. x50, x100), so your profit or loss moves in proportion to that multiplier rather than 1:1 with the stake. This means small price movements can produce outsized gains or losses.',
                    'Multipliers include a stop-out level, which automatically closes your position if losses reach your invested stake, preventing your account balance from going negative on that trade.',
                ],
            },
            {
                heading: 'Risk management tools within multipliers',
                bullets: [
                    'Stop loss — automatically closes the trade at a defined loss amount.',
                    'Take profit — automatically closes the trade once a target profit is reached.',
                    'Deal cancellation — an optional feature (for an added cost) that lets you cancel a losing trade within a set time window.',
                ],
            },
        ],
        keyTakeaway: 'Multipliers turn small price moves into amplified profit or loss — always set a stop loss and size your stake conservatively when using leverage.',
    },
    {
        id: 'l12',
        tag: 'Contract Types',
        title: '12. Accumulators Explained',
        intro: 'Accumulators grow your payout with every tick that price stays within a dynamic range, resetting your risk if the range is breached.',
        sections: [
            {
                heading: 'How accumulators work',
                paragraphs: [
                    'When you enter an Accumulator contract, you choose a growth rate. As long as the price stays within a boundary that recalculates each tick, your potential payout grows tick by tick. If the price moves outside that boundary at any point, the contract ends and you lose your stake.',
                    'You can manually take profit at any time before the boundary is breached, giving you control over when to lock in gains versus continuing to let the payout accumulate.',
                ],
            },
            {
                heading: 'Key considerations',
                bullets: [
                    'Higher growth rates offer faster payout growth but come with a tighter price boundary, increasing the chance of an early exit.',
                    'Lower growth rates grow more slowly but allow a wider boundary, reducing the chance of hitting the limit quickly.',
                    'Because there is no fixed duration, discipline in deciding when to cash out is essential.',
                ],
            },
        ],
        keyTakeaway: 'Accumulators reward patience with compounding payout growth, but require you to actively decide when to take profit before the price breaches its boundary.',
    },
    {
        id: 'l13',
        tag: 'Automation',
        title: '13. Introduction to Deriv Bot (DBot)',
        intro: 'DBot is Deriv\'s visual, block-based tool that lets you build automated trading strategies without writing a single line of code.',
        sections: [
            {
                heading: 'What DBot lets you do',
                paragraphs: [
                    'DBot uses draggable blocks, similar to a flowchart, to define trade conditions, entry logic, stake management, and exit rules. Once built, your bot can run automatically, executing trades based on the exact logic you designed, without manual clicking on every trade.',
                ],
            },
            {
                heading: 'Core parts of a DBot strategy',
                bullets: [
                    'Trade parameters — market, contract type, and basic settings.',
                    'Purchase conditions — the rules that decide when to enter a trade.',
                    'Restart/reset conditions — logic for what happens after a trade completes (win or loss).',
                    'Stake management blocks — logic for adjusting the next stake, e.g. flat stake or martingale-style progression.',
                ],
            },
            {
                heading: 'Getting bots into your account',
                paragraphs: [
                    'You can build a bot from scratch using the block editor, import an existing bot as an XML file, or use pre-built strategies shared by the community — always test any bot thoroughly on a demo account before running it with real funds.',
                ],
            },
        ],
        keyTakeaway: 'DBot turns a trading idea into repeatable, automated logic — but the quality of the bot still depends entirely on the strategy and risk rules you design into it.',
    },
    {
        id: 'l14',
        tag: 'Automation',
        title: '14. Building Your First DBot Strategy',
        intro: 'A simple, well-structured bot is more valuable than a complex one you don\'t fully understand — start with the basics and build up.',
        sections: [
            {
                heading: 'A basic strategy blueprint',
                paragraphs: [
                    'A typical beginner bot might trade Rise/Fall on a Volatility Index, entering after a simple condition is met (such as a set number of consecutive same-direction ticks), using a small, fixed stake, and stopping after reaching a defined profit target or loss limit for the session.',
                ],
            },
            {
                heading: 'Essential elements to include',
                bullets: [
                    'A clear entry condition based on observable price data, not guesswork.',
                    'A defined stake size appropriate to your account balance.',
                    'A daily loss limit that stops the bot automatically once reached.',
                    'A daily profit target that stops the bot once reached, to lock in gains.',
                ],
            },
            {
                heading: 'Testing before going live',
                paragraphs: [
                    'Always run a new bot on a demo account first, across different market conditions, to see how it behaves. A strategy that performs well in one type of market (e.g. trending) may perform poorly in another (e.g. choppy, sideways price action).',
                ],
            },
        ],
        keyTakeaway: 'Start simple: one clear entry rule, a sensible stake, and firm profit/loss limits — complexity should only be added once you understand how the basics behave.',
    },
    {
        id: 'l15',
        tag: 'Technical Analysis',
        title: '15. Reading Candlestick Charts',
        intro: 'Candlestick charts are the standard way traders visualise price movement, showing open, high, low, and close for each time period at a glance.',
        sections: [
            {
                heading: 'Anatomy of a candlestick',
                paragraphs: [
                    'Each candle has a body, showing the range between the opening and closing price, and wicks (or shadows), showing the highest and lowest prices reached during that period. A candle where the close is higher than the open is typically shown as bullish (often green or white); one where the close is lower is bearish (often red or black).',
                ],
            },
            {
                heading: 'What candles can tell you',
                bullets: [
                    'Long bodies suggest strong momentum in one direction.',
                    'Long wicks suggest rejection of a price level, where the market tried to move but was pushed back.',
                    'Small bodies with long wicks (like a doji) often suggest indecision between buyers and sellers.',
                    'Patterns formed by multiple candles together, such as engulfing patterns, can signal potential reversals.',
                ],
            },
        ],
        keyTakeaway: 'Candlesticks compress a lot of information into one shape — learn to read body size, wick length, and colour together, not in isolation.',
    },
    {
        id: 'l16',
        tag: 'Technical Analysis',
        title: '16. Support, Resistance, and Trend Lines',
        intro: 'Support, resistance, and trend lines are among the most fundamental tools for understanding where price is likely to react.',
        sections: [
            {
                heading: 'Support and resistance',
                paragraphs: [
                    'Support is a price level where downward movement has historically paused or reversed, as buying interest increases. Resistance is the opposite — a level where upward movement has historically paused or reversed, as selling interest increases. These levels are not exact lines but zones, and they can be broken when the market has strong enough momentum.',
                ],
            },
            {
                heading: 'Trend lines and channels',
                paragraphs: [
                    'A trend line connects a series of higher lows in an uptrend or lower highs in a downtrend, helping visualise the direction and strength of a trend. When price moves between two parallel trend lines, this is called a channel, and traders often look for reactions at the channel\'s edges.',
                ],
            },
            {
                heading: 'Practical tips',
                bullets: [
                    'The more times a level has been tested and held, the more significant it tends to be considered.',
                    'A broken support level often becomes resistance later, and vice versa — this is called a "role reversal".',
                    'Combine support/resistance with other tools rather than trading off them alone.',
                ],
            },
        ],
        keyTakeaway: 'Support, resistance, and trend lines map out the "memory" of a market — where price has reacted before is often where it reacts again.',
    },
    {
        id: 'l17',
        tag: 'Technical Analysis',
        title: '17. Key Indicators: Moving Averages and RSI',
        intro: 'Moving averages and the Relative Strength Index (RSI) are two of the most widely used indicators for identifying trend and momentum.',
        sections: [
            {
                heading: 'Moving averages',
                paragraphs: [
                    'A moving average smooths out price data by calculating the average price over a set number of periods, helping filter out short-term noise to reveal the underlying trend. A Simple Moving Average (SMA) weighs all periods equally, while an Exponential Moving Average (EMA) gives more weight to recent price data, making it react faster to new information.',
                    'Traders often watch for "crossovers" — when a faster moving average crosses above or below a slower one — as a potential signal of a change in trend direction.',
                ],
            },
            {
                heading: 'Relative Strength Index (RSI)',
                paragraphs: [
                    'RSI is a momentum oscillator, typically scaled from 0 to 100, that measures the speed and size of recent price changes. Readings above 70 are traditionally considered "overbought" and readings below 30 are considered "oversold", though in strong trends the market can remain in these zones for extended periods.',
                ],
            },
        ],
        keyTakeaway: 'Moving averages help identify trend direction; RSI helps gauge momentum and potential exhaustion — using them together provides more context than either alone.',
    },
    {
        id: 'l18',
        tag: 'Technical Analysis',
        title: '18. Key Indicators: Bollinger Bands and MACD',
        intro: 'Bollinger Bands and MACD are popular tools for reading volatility and trend momentum respectively.',
        sections: [
            {
                heading: 'Bollinger Bands',
                paragraphs: [
                    'Bollinger Bands consist of a moving average with two bands plotted above and below it, based on price volatility (standard deviation). When volatility increases, the bands widen; when volatility decreases, they contract. Price touching or exceeding a band doesn\'t automatically mean reversal — it can also signal a strong trending move, especially during a "band squeeze" breakout.',
                ],
            },
            {
                heading: 'MACD (Moving Average Convergence Divergence)',
                paragraphs: [
                    'MACD tracks the relationship between two exponential moving averages, plotted alongside a signal line and a histogram. Crossovers between the MACD line and the signal line are commonly used to identify potential shifts in momentum, while the histogram shows the strength of that momentum visually.',
                ],
            },
            {
                heading: 'Combining indicators wisely',
                bullets: [
                    'Avoid stacking multiple indicators that measure the same thing (e.g. several momentum oscillators) — this creates false confirmation.',
                    'Pair a trend indicator (like a moving average) with a momentum indicator (like RSI or MACD) for a more balanced view.',
                    'Indicators are lagging by nature since they are calculated from past price — treat them as supporting evidence, not certainty.',
                ],
            },
        ],
        keyTakeaway: 'Bollinger Bands reveal volatility conditions while MACD reveals momentum shifts — combining a small, complementary toolkit beats overloading your chart with indicators.',
    },
    {
        id: 'l19',
        tag: 'Strategy',
        title: '19. Trend-Following vs Range-Trading Strategies',
        intro: 'Most trading strategies fall into one of two broad categories: following an established trend, or trading within a defined range.',
        sections: [
            {
                heading: 'Trend-following',
                paragraphs: [
                    'Trend-following strategies aim to enter in the direction of an established move and stay in as long as the trend continues, exiting when signs of reversal appear. These strategies tend to perform well in strongly trending markets like Boom/Crash indices or trending forex pairs, but can produce frequent small losses during choppy, sideways conditions.',
                ],
            },
            {
                heading: 'Range-trading',
                paragraphs: [
                    'Range-trading strategies assume price will oscillate between a support and resistance zone, buying near support and selling near resistance. These work well in calmer, sideways markets, but can suffer large losses if the market suddenly breaks out of the range.',
                ],
            },
            {
                heading: 'Matching strategy to market condition',
                bullets: [
                    'Identify whether the market is currently trending or ranging before choosing your approach.',
                    'Avoid applying a range strategy during a strong trend, and vice versa.',
                    'Some traders use volatility and price-structure signals specifically to detect which condition is currently active.',
                ],
            },
        ],
        keyTakeaway: 'No single strategy works in every market condition — recognising whether a market is trending or ranging is often more important than the strategy itself.',
    },
    {
        id: 'l20',
        tag: 'Strategy',
        title: '20. Understanding the Martingale Strategy',
        intro: 'Martingale is a well-known staking method that increases stake size after a loss, aiming to recover previous losses with a single win.',
        sections: [
            {
                heading: 'How it works',
                paragraphs: [
                    'In its classic form, Martingale doubles the stake after every loss so that, when a win eventually occurs, it recovers all previous losses in that sequence plus a small profit equal to the original stake. It resets back to the base stake after any win.',
                ],
            },
            {
                heading: 'Why it is risky',
                bullets: [
                    'Stakes grow exponentially during a losing streak, which can rapidly exhaust your account balance.',
                    'Trading platforms and account balances impose practical limits, meaning a long enough losing streak makes recovery impossible.',
                    'It does not improve your actual win probability — it only changes how losses and wins are distributed in size.',
                ],
            },
            {
                heading: 'Safer variations',
                paragraphs: [
                    'Some traders use a modified or "capped" Martingale, limiting the number of consecutive stake increases, or combine it with a strict overall loss limit for the session. These variations reduce, but do not eliminate, the underlying risk of exponential stake growth.',
                ],
            },
        ],
        keyTakeaway: 'Martingale can look effective over short winning stretches, but a single extended losing streak can wipe out an account — use it, if at all, with strict caps and full awareness of the risk.',
    },
    {
        id: 'l21',
        tag: 'Risk Management',
        title: '21. Position Sizing and Money Management',
        intro: 'How much you stake on each trade often matters more to long-term survival than which individual trades you win or lose.',
        sections: [
            {
                heading: 'Why position sizing matters',
                paragraphs: [
                    'Even a strategy with a strong win rate can lose money overall if position sizes are too large relative to the account, because a handful of losses can outweigh many small wins. Conversely, disciplined position sizing lets a trader survive losing streaks long enough for a sound strategy to play out.',
                ],
            },
            {
                heading: 'Common position sizing guidelines',
                bullets: [
                    'Many traders risk only a small, fixed percentage of their account (commonly cited around 1–2%) on any single trade.',
                    'Keep stake sizes consistent unless following a deliberate, pre-planned staking system.',
                    'Reduce stake size after a losing streak rather than increasing it, unless using a specifically tested progression strategy.',
                    'Account for the total exposure across multiple open positions, not just one trade at a time.',
                ],
            },
        ],
        keyTakeaway: 'Consistent, modest position sizing protects your capital through inevitable losing streaks — it is one of the few things a trader fully controls.',
    },
    {
        id: 'l22',
        tag: 'Risk Management',
        title: '22. Stop Loss, Take Profit, and Daily Limits',
        intro: 'Defining your exit points before entering a trade removes emotion from the decision and protects your capital from runaway losses.',
        sections: [
            {
                heading: 'Stop loss and take profit',
                paragraphs: [
                    'A stop loss defines the maximum loss you are willing to accept on a trade before it closes automatically. A take profit defines the level at which you\'ll lock in gains. On Multiplier and CFD-style contracts, these can typically be set directly on the trade; on fixed-payout options, the "stop loss" is effectively built into your stake since the maximum loss is the amount staked.',
                ],
            },
            {
                heading: 'Session and daily limits',
                bullets: [
                    'Daily loss limit — stop trading for the day once a defined loss amount is reached, to prevent emotional "revenge trading".',
                    'Daily profit target — consider stopping once a reasonable profit goal is met, rather than risking gains chasing more.',
                    'Maximum number of trades per session — limits overtrading driven by boredom or frustration.',
                ],
            },
            {
                heading: 'Why limits are hard to follow — and why they matter anyway',
                paragraphs: [
                    'Discipline around limits is often harder in practice than in theory, especially after a loss triggers the urge to "win it back". Setting these rules in advance, and where possible automating them (e.g. through DBot\'s stop conditions), removes the need to rely on willpower in the moment.',
                ],
            },
        ],
        keyTakeaway: 'Decide your stop loss, take profit, and daily limits before you start trading — not in the middle of a losing streak when judgement is most compromised.',
    },
    {
        id: 'l23',
        tag: 'Trading Psychology',
        title: '23. Trading Psychology and Emotional Discipline',
        intro: 'Many experienced traders argue that psychology and discipline matter more to long-term results than any single strategy or indicator.',
        sections: [
            {
                heading: 'Common emotional traps',
                bullets: [
                    'Revenge trading — increasing stake size or trade frequency after a loss to "win it back" quickly.',
                    'FOMO (fear of missing out) — entering a trade impulsively because price is moving without you.',
                    'Overconfidence after a winning streak — abandoning risk rules because recent trades felt "easy".',
                    'Analysis paralysis — overthinking every trade to the point of missing valid opportunities or acting inconsistently.',
                ],
            },
            {
                heading: 'Building discipline',
                paragraphs: [
                    'Discipline is easier to maintain when trading decisions are pre-planned rather than made in the moment. Defining your entry rules, stake size, and exit conditions before the trading session starts — and sticking to them regardless of how you "feel" mid-session — reduces the influence of emotion on outcomes.',
                    'Taking breaks after a loss, journaling your emotional state alongside your trades, and setting hard daily limits are all practical techniques to keep emotions from overriding your plan.',
                ],
            },
        ],
        keyTakeaway: 'A mediocre strategy followed with discipline often outperforms an excellent strategy abandoned emotionally at the first difficult moment.',
    },
    {
        id: 'l24',
        tag: 'Trading Psychology',
        title: '24. Common Mistakes New Traders Make',
        intro: 'Recognising frequent beginner mistakes ahead of time can help you avoid repeating them with real money.',
        sections: [
            {
                heading: 'Frequent pitfalls',
                bullets: [
                    'Trading without a plan — entering trades based on impulse rather than a defined rule set.',
                    'Risking too much per trade — sizing stakes based on desired profit rather than acceptable loss.',
                    'Ignoring account balance context — treating a small account the same as a large one without adjusting stake size.',
                    'Chasing losses with bigger stakes instead of stepping back and reassessing.',
                    'Skipping demo testing — moving to a real account before validating a strategy works consistently.',
                    'Over-optimising a bot or strategy to fit past data perfectly, which often fails on new, unseen price action ("overfitting").',
                ],
            },
            {
                heading: 'How to correct course',
                paragraphs: [
                    'Most of these mistakes are addressed by the same core habits: define your rules before trading, size positions conservatively, test thoroughly on demo, and review your results honestly and regularly rather than only when things go wrong.',
                ],
            },
        ],
        keyTakeaway: 'Nearly every common trading mistake stems from skipping preparation — a clear plan, tested in advance, prevents most of the errors listed here.',
    },
    {
        id: 'l25',
        tag: 'Putting It Together',
        title: '25. Building a Trading Plan and Keeping a Journal',
        intro: 'This final lesson brings everything together into a practical framework you can use for every trading session going forward.',
        sections: [
            {
                heading: 'What a trading plan should define',
                bullets: [
                    'Markets you will trade and why (e.g. Volatility 75 for its steady tick generation and known behaviour).',
                    'Contract types and entry conditions you will use, stated clearly enough that someone else could follow them.',
                    'Stake size and position sizing rules relative to your account balance.',
                    'Stop loss, take profit, and daily loss/profit limits.',
                    'Rules for when you will stop trading for the day, regardless of outcome.',
                ],
            },
            {
                heading: 'Why a trading journal matters',
                paragraphs: [
                    'A trading journal records each trade — market, contract type, stake, outcome, and your reasoning at the time — allowing you to review performance objectively rather than relying on memory or feelings. Over time, this data reveals which conditions, contract types, or times of day actually work for you, and which ones consistently don\'t.',
                ],
            },
            {
                heading: 'Continuous improvement',
                paragraphs: [
                    'Review your journal regularly (weekly is common) to identify patterns in your wins and losses. Adjust your trading plan gradually based on evidence from your own results, rather than frequently switching strategies based on a single good or bad session.',
                ],
            },
        ],
        keyTakeaway: 'A written trading plan combined with an honest journal turns trading from a series of isolated bets into a process you can measure, learn from, and steadily improve.',
    },
];
