import { api_base } from '@/external/bot-skeleton';

export type TCopierSettings = {
    max_trade_stake?: number;
    min_trade_stake?: number;
    trade_types?: string[];
};

export type TCopyTradingStats = {
    active_since?: number;
    avg_duration?: string;
    avg_loss?: number;
    avg_profit?: number;
    avg_stake?: number;
    breakeven_trades_percentage?: number;
    copiers?: number;
    last_updated?: number;
    losing_trades_percentage?: number;
    monthly_profitable_trades?: Record<string, number>;
    performance_probability?: number;
    profitable_trades_percentage?: number;
    total_profitable_runs?: number;
    total_trades?: number;
    trades_breakdown?: Record<string, number>;
    trades_profitable_breakdown?: Record<string, number>;
    yearly_profitable_trades?: Record<string, number>;
};

const throwIfError = (response: any, fallback_message: string) => {
    if (response?.error) {
        throw new Error(response.error.message || fallback_message);
    }
    return response;
};

const ensureAuthorized = async () => {
    if (api_base.is_authorized) return;
    await (api_base as any).authorizeAndSubscribe?.();
    if (!api_base.is_authorized) {
        throw new Error('Please log in to your Deriv account before using Copy Trading.');
    }
};

/**
 * Starts copying another trader's real-money trades into the currently
 * authorized account. `master_token` must be a read-only API token
 * generated by the trader being copied (with `allow_copiers` enabled).
 */
export const startCopyTrading = async (master_token: string, settings: TCopierSettings = {}) => {
    await ensureAuthorized();

    const request: Record<string, unknown> = { copy_start: master_token.trim() };
    if (settings.max_trade_stake) request.max_trade_stake = settings.max_trade_stake;
    if (settings.min_trade_stake) request.min_trade_stake = settings.min_trade_stake;
    if (settings.trade_types?.length) request.trade_types = settings.trade_types;

    const response = await (api_base.api as any).send(request);
    return throwIfError(response, 'Unable to start copy trading with this token.');
};

/** Stops copying the trader identified by the given read-only token. */
export const stopCopyTrading = async (master_token: string) => {
    await ensureAuthorized();

    const response = await (api_base.api as any).send({ copy_stop: master_token.trim() });
    return throwIfError(response, 'Unable to stop copy trading.');
};

/** Fetches performance/risk/copier statistics for the account behind the given token. */
export const fetchCopyTradingStatistics = async (master_token: string): Promise<TCopyTradingStats> => {
    await ensureAuthorized();

    const response = await (api_base.api as any).send({
        copytrading_statistics: 1,
        trader_id: master_token.trim(),
    });
    const result = throwIfError(response, 'Unable to fetch trader statistics.');
    return (result?.copytrading_statistics ?? {}) as TCopyTradingStats;
};

/** Fetches the current account's own copiers list / active copy relationships, when available. */
export const fetchCopiersList = async () => {
    await ensureAuthorized();

    const response = await (api_base.api as any).send({ copytrading_list: 1 });
    return throwIfError(response, 'Unable to fetch copiers list.');
};

/** Enables or disables `allow_copiers` on the currently authorized (real-money) account. */
export const setAllowCopiers = async (allow: boolean) => {
    await ensureAuthorized();

    const response = await (api_base.api as any).send({
        set_settings: 1,
        allow_copiers: allow ? 1 : 0,
    });
    return throwIfError(response, 'Unable to update copy trading permission.');
};
